repos:
  - repo: https://github.com/nix-community/nixfmt
    rev: v0.6.0
    hooks:
      - id: nixfmt
        files: \.nix$

  - repo: https://github.com/nix-community/statix
    rev: v0.2.1
    hooks:
      - id: statix
        files: \.nix$
        args: [--fix, --quiet]
